services:
  gateway-api:
    build: .
    ports:
      - "8000:8000"

    volumes:
      - ${DATA_DIR:-./data}:/app/data:ro
      - ./:/host-output

    environment:
      - PYTHONUNBUFFERED=1
      - DATA_DIR=/app/data
      - OUTPUT_PATH=/host-output/predictions.csv